name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Release
        run: make release -f github-actions.mak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
